-- SUPERSEDED — do not run this file.
--
-- This used to create the events table with the policy:
--     for all using (true) with check (true)
-- which let anyone holding the public anon key read, edit and delete events.
--
-- Use security.sql instead. It adds the published / signup_url / age_range
-- columns and replaces the open policies with:
--     public  -> may read published events only
--     admin   -> signed in, may do everything
--
-- Kept as an empty stub so nobody runs the old version by accident.
-- Safe to delete once you're happy the new policies are working.
