#!/usr/bin/env python3
"""Convert the Google Fonts TTFs in this folder to WOFF2 and emit fonts.css.

Run from this folder:  python3 build-fonts.py

Only the weights the site actually uses are converted. Variable fonts are
handled too — Google now ships some families as a single variable file, which
we instance down to each static weight we need.
"""

import pathlib, sys
from fontTools.ttLib import TTFont

HERE = pathlib.Path(__file__).parent

# family -> {weight: italic?}
WANTED = {
    'ZillaSlab': {500: False, 600: False, 700: False},
    'Caveat':    {600: False, 700: False},
    'Nunito':    {400: False, 600: False, 700: False, 800: False, '400i': True},
}
FAMILY_CSS = {'ZillaSlab': 'Zilla Slab', 'Caveat': 'Caveat', 'Nunito': 'Nunito'}
NAMES = {400: 'Regular', 500: 'Medium', 600: 'SemiBold', 700: 'Bold', 800: 'ExtraBold'}


def find_ttfs():
    return sorted(p for p in HERE.rglob('*.ttf') if p.is_file())


def is_variable(font):
    return 'fvar' in font


def instance(font, weight):
    from fontTools.varLib.instancer import instantiateVariableFont
    return instantiateVariableFont(font, {'wght': weight}, inplace=False)


def main():
    ttfs = find_ttfs()
    if not ttfs:
        sys.exit("No .ttf files found here. Download the families first — see README.md.")

    print(f"Found {len(ttfs)} TTF file(s).\n")
    faces, made = [], 0

    for fam, weights in WANTED.items():
        for key, italic in weights.items():
            weight = int(str(key).rstrip('i'))
            style_word = NAMES[weight]

            # Prefer an exact static file, then fall back to a variable one.
            want_italic = italic
            static = next((p for p in ttfs
                           if fam.lower() in p.stem.lower().replace('-', '').replace('_', '')
                           and style_word.lower() in p.stem.lower().replace('-', '')
                           and (('italic' in p.stem.lower()) == want_italic)), None)
            varfile = next((p for p in ttfs
                            if fam.lower() in p.stem.lower().replace('-', '').replace('_', '')
                            and ('italic' in p.stem.lower()) == want_italic
                            and is_variable(TTFont(p))), None)

            src, font = None, None
            if static:
                src, font = static, TTFont(static)
            elif varfile:
                src = varfile
                font = instance(TTFont(varfile), weight)

            if font is None:
                print(f"  !  {fam} {weight}{'i' if italic else ''}: no matching file, skipped")
                continue

            out = HERE / f"{fam}-{weight}{'italic' if italic else ''}.woff2"
            font.flavor = 'woff2'
            font.save(out)
            made += 1
            print(f"  ok {out.name:<32} {out.stat().st_size/1024:6.1f} KB   (from {src.name})")

            faces.append(
                "@font-face{{font-family:'{f}';font-style:{s};font-weight:{w};"
                "font-display:swap;src:url('fonts/{file}') format('woff2')}}".format(
                    f=FAMILY_CSS[fam], s='italic' if italic else 'normal',
                    w=weight, file=out.name))

    if not made:
        sys.exit("\nNothing converted — check the TTFs are in this folder.")

    (HERE / 'fonts.css').write_text(
        "/* Generated by build-fonts.py — self-hosted so no visitor IP reaches Google. */\n"
        + "\n".join(faces) + "\n", encoding='utf-8')

    print(f"\nWrote fonts.css with {made} face(s).\n")
    print("Now, in index.html / privacy.html / terms.html:")
    print("  1. delete the three <link> tags pointing at fonts.googleapis.com / gstatic.com")
    print("  2. add:  <link rel=\"stylesheet\" href=\"fonts/fonts.css\">")
    print("  3. remove the Google Fonts row from the privacy policy tables (EN + IT)")


if __name__ == '__main__':
    main()
